[project]
name = "drake-control-filter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "drake>=1.45.0",
    "manipulation>=2025.9.23",
    "numpy>=2.3.3",
]
